
#ifndef __FX_OS_BUILD_PARAMETERS_
#define __FX_OS_BUILD_PARAMETERS_

#define FXOS_BUILD_NEAR_HEAP_ADDR	(0x060000)
#define FXOS_BUILD_NEAR_HEAP_TOP	(0x06FFFF)

#define FXOS_BUILD_FAR_HEAP_SEG	    ($19:0000)
#define FXOS_BUILD_FAR_HEAP_ADDR	(0x190000)
#define FXOS_BUILD_FAR_HEAP_SIZE	(0x030000)


#endif
